/* ============================================================================
   كله — Kollo | Database Schema Definition
   ============================================================================ */
const SCHEMA = {
  tasks: ['status', 'due', 'projectId', 'priority', '*tags'],
  projects: ['status'],
  habits: ['active'],
  habitLogs: ['habitId', 'date', 'habitId+date'],
  events: ['start'],
  notes: ['updatedAt', '*tags'],
  noteLinks: ['from', 'to'],
  accounts: ['type'],
  txns: ['date', 'accountId', 'categoryId', 'type'],
  categories: ['kind'],
  budgets: ['month', 'categoryId'],
  debts: ['dir', 'status'],
  installments: ['due', 'status'],
  subscriptions: ['nextDue'],
  gam3iyat: ['status'],
  goals: ['status'],
  keyResults: ['goalId'],
  people: ['birthday', 'lastContact'],
  socialDuties: ['date', 'personId'],
  healthLogs: ['type', 'date', 'type+date'],
  meds: ['active'],
  medDoses: ['medId', 'date'],
  moodLogs: ['date'],
  journal: ['date'],
  books: ['status'],
  courses: ['status'],
  cards: ['due', 'noteId'],
  assets: ['category'],
  warranties: ['expiry'],
  vehicles: [],
  maintenance: ['vehicleId', 'due'],
  bills: ['kind', 'date'],
  documents: ['expiry', 'kind'],
  attachments: ['refId'],
  shoppingItems: ['done'],
  pantry: ['expiry'],
  recipes: [],
  timeLogs: ['date', 'projectId'],
  pomodoros: ['date'],
  automations: ['active'],
  aiChats: ['updatedAt'],
  aiMessages: ['chatId'],
  aiToolCalls: ['chatId', 'batchId'],
  clients: [],
  invoices: ['status', 'due'],
  worship: ['date', 'kind'],
  settings: [],
  trash: ['store', 'deletedAt'],
  activityLog: ['at']
};

window.SCHEMA = SCHEMA;
